source 'https://github.com/CocoaPods/Specs.git'
#source 'https://gitee.com/liangyujuan/kykj-hospital-custom-im-sdkspec.git'

#post_install do |installer|
#  installer.pods_project.build_configurations.each do |config|
#    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#  end
#end


use_frameworks!
#inhibit_all_warnings!
#use_modular_headers!

platform :ios, '10.0'

target 'KykjHospitalCustomImSDK_Example' do
  pod 'KykjHospitalCustomImSDK', :path => '../KykjHospitalCustomImSDK.podspec'

#  pod 'KykjHospitalCustomImSDK', :git => 'https://gitee.com/liangyujuan/kykj-hospital-custom-im-sdk' , :tag => '1.0.0'

#pod 'KykjHospitalCustomImSDK', '~> 1.0.0'

  target 'KykjHospitalCustomImSDK_Tests' do
    inherit! :search_paths

    
  end
end
